package(default_visibility = ["//visibility:public"])


cc_library(
    name = "java_scriptoptionlines",
    hdrs = [":converter.h"],
    srcs = [":arser.h", ":converter.h", ":converter.cc", ":parserlegacy.h", ":parserlegacy.cc"],
    deps = ["//base/script_options_parser:scriptoptionlinesparser", "//base/exaudflib:header", "//base/exaudflib:exaudflib-deps"],
)
