cc_test(
    name = "script-options-legacy-parser-test",
    srcs = ["script_option_lines_test.cpp"],
    deps = [
        "//script_options_parser/legacy:script_option_lines_parser_legacy",
        "@googletest//:gtest_main",
    ],
)