FROM exaudf/baseimage_python3-ds-exasol-6.1.0

RUN mkdir /exaudf_src /exaudf_src/build /exaudf

COPY src/ /exaudf_src/

RUN /exaudf_src/build_client.sh --src-dir=/exaudf_src --build-dir=/exaudf_src/build --output-dir=/exaudf --enable-python --python-version=python3.6
