package(default_visibility = ["//visibility:public"])

cc_library(
    name = "streamingcontainer",
    srcs = ["streamingcontainer.cc","streamingcontainer.h"],
    hdrs = ["streamingcontainer.h"],
    deps = ["//exaudf/exaudflib:exaudflib-deps","//exaudf/exaudflib:header"]
)