language: python

# Setting sudo to false will cause Travis to use Containers (default in the meantime)
sudo: true

services:
    - docker


install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq unixodbc unixodbc-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libodbcinst.so.1 /usr/lib/x86_64-linux-gnu/libodbcinst.so.2

matrix:
  include:
  - name: mini
    env: MATRIX_FLAVOR=mini
  - name: standard
    env: MATRIX_FLAVOR=standard

script:
  - ./build --flavor=$MATRIX_FLAVOR
  - ./export --flavor=$MATRIX_FLAVOR
  - ./test --flavor $MATRIX_FLAVOR
