#!/bin/sh
die() { echo "ERROR:" "$@" >&2; exit 1; }


optarr=$(getopt -o 'h' --long 'help,flavor:' -- "$@")

eval set -- "$optarr"

while true; do
    case "$1" in
        --flavor) FLAVOR="$2"; shift 2;;
        -h|--help) echo "Usage: $0"
		   echo "Options:"
		   echo "  [--flavor]     Choose between different versions"
		   echo "  [-h|--help]    Print this help."; exit 0;;
        --) shift; break;;
        *) echo "Internal error while parsing arguments. ($1)"; exit 1;;
    esac
done




echo Removing all exited containers:
CONTAINERS=$(docker ps -a -f status=exited -q)
if [ ! X"$CONTAINERS" = X"" ]; then  
    docker rm $CONTAINERS
fi


if [ "X$FLAVOR" = "X" ]; then
    echo "No --flavor given. Not removing any images"
else
    echo Removing all images for the selected flavor
    docker images --filter "reference=exaudf/*_$FLAVOR" -q | xargs docker rmi
fi
