#!/bin/sh
die() { echo "ERROR:" "$@" >&2; exit 1; }

set -x

optarr=$(getopt -o 'h' --long 'help,flavor:' -- "$@")

eval set -- "$optarr"

while true; do
    case "$1" in
        --flavor) FLAVOR="$2"; shift 2;;
        -h|--help) echo "Usage: $0"
		   echo "Options:"
		   echo "  [--flavor]     Choose between different versions of the Dockerfiles (added as _<flavor> suffix)"
		   echo "  [-h|--help]    Print this help."; exit 0;;
        --) shift; break;;
        *) echo "Internal error while parsing arguments. ($1)"; exit 1;;
    esac
done

[ "X$FLAVOR" = "X" ] && die "Missing mandatory argument --flavor"

docker build . --tag exaudf/test_$FLAVOR -f flavors/$FLAVOR/Dockerfile.test_$FLAVOR

docker run --detach --security-opt seccomp=unconfined --name test_container_$FLAVOR exaudf/test_$FLAVOR sleep 1000000

docker exec test_container_$FLAVOR mkfifo /tmp/fff

#docker exec --detach test_container_$FLAVOR bash -c 'python exasol_emulator/exasolution.py unix:/tmp/fff exasol_emulator/input2.csv exasol_emulator/output.csv exasol_emulator/script_fr.py'
#docker exec --detach test_container_$FLAVOR python exasol_emulator/exasolution.py unix:/tmp/fff exasol_emulator/input2.csv exasol_emulator/output.csv exasol_emulator/script2.py
#docker exec test_container_$FLAVOR /exaudf/exaudfclient ipc:///tmp/fff lang=streaming

#docker exec --detach test_container_$FLAVOR python exasol_emulator/exasolution.py unix:/tmp/fff exasol_emulator/input.csv exasol_emulator/output.csv exasol_emulator/script.py
#docker exec test_container_$FLAVOR /exaudf/exaudfclient ipc:///tmp/fff lang=r
#docker exec -it test_container_$FLAVOR gdb /exaudf/exaudfclient

# /opt/conda/bin/python exasol_emulator/exasolution.py unix:/tmp/fff exasol_emulator/input2.csv exasol_emulator/output.csv exasol_emulator/script.py &
# python exasol_emulator/exasolution.py unix:/tmp/fff exasol_emulator/input2.csv exasol_emulator/output.csv exasol_emulator/script.py&
# /exaudf/exaudfclient ipc:///tmp/fff lang=python

docker exec --detach test_container_$FLAVOR bash -c 'python exasol_emulator/exasolution.py unix:/tmp/fff exasol_emulator/input2.csv exasol_emulator/output.csv exasol_emulator/get_connections_script.py'

docker exec -it test_container_$FLAVOR bash -c '/exaudf/exaudfclient ipc:///tmp/fff lang=python'

#docker exec -it test_container_$FLAVOR /bin/bash

#docker exec test_container_$FLAVOR cat exasol_emulator/output.csv
docker rm -f test_container_$FLAVOR
