#!/bin/bash

# This script acts as the start of exaslct the script language container build tool
# It tries to discover if pipenv is already installed or tries to install it if it not exists.
# After that it creates the virtual environment and install all necessary dependencies for exaslct.
# In the end it runs exaslct_src/exaslct.py in the virtual environment.

COMMAND_LINE_ARGS=$*
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

source pipenv_utils.sh

run () {
    export PYTHONPATH="$SCRIPT_DIR"
    $PIPENV_BIN run python3 "$SCRIPT_DIR/exaslct_src/exaslct.py" $COMMAND_LINE_ARGS
}

discover_pipenv
init_pipenv "$PIPENV_BIN"
run "$PIPENV_BIN"
