#!/bin/sh
die() { echo "ERROR:" "$@" >&2; exit 1; }


optarr=$(getopt -o 'h' --long 'help,flavor:,target:' -- "$@")

eval set -- "$optarr"

while true; do
    case "$1" in
        --flavor) FLAVOR="$2"; shift 2;;
        --target) TARGET="$2"; shift 2;;
        -h|--help) echo "Usage: $0"
		   echo "Options:"
		   echo "  [--target]     result file: exports/<target-name>.tar.gz"
		   echo "  [--flavor]     Choose between different versions of the Dockerfiles (added as _<flavor> suffix)"
		   echo "  [-h|--help]    Print this help."; exit 0;;
        --) shift; break;;
        *) echo "Internal error while parsing arguments. ($1)"; exit 1;;
    esac
done


[ "X$TARGET" = "X" ] && die "Missing mandatory argument --target"
[ "X$FLAVOR" = "X" ] && die "Missing mandatory argument --flavor"

docker run --name releasecontainer exaudf/release_$FLAVOR
echo "Exporting into target exports/$TARGET"
mkdir -p tmp
mkdir -p exports
PREP="./tmp/$TARGET"
docker export releasecontainer -o "$PREP.tar"
echo Cleanup Docker
docker stop releasecontainer
docker rm releasecontainer
echo Preparing Container:
echo 1. Unpack
mkdir -p $PREP && rm -rf $PREP/*
tar xf "$PREP.tar" -C "$PREP/" --exclude=dev --exclude=proc
echo 2. Creating Dirs
mkdir $PREP/conf $PREP/proc $PREP/dev $PREP/buckets
echo 3. Creating links
rm $PREP/etc/resolv.conf $PREP/etc/hosts
ln -s /conf/resolv.conf $PREP/etc/resolv.conf
ln -s /conf/hosts $PREP/etc/hosts
echo 4. Package
tar -C $PREP -zcf $PREP.tar.gz $(ls $PREP)
mv $PREP.tar.gz exports 
echo 5. Cleanup temp files
rm -rf $PREP.tar $PREP
echo done exporting
echo ----------------------------
echo "curl template: (for a bucketfs that is running on port 2580 at 192.168.122.158):"
echo 
echo "curl -v -X PUT -T exports/$TARGET.tar.gz http://w:w@192.168.122.158:2580/bucketname/$TARGET.tar.gz"
echo
echo SQL-template:
echo 
echo "ALTER SESSION SET SCRIPT_LANGUAGES='MYPYTHON=localzmq+protobuf:///bucketfsname/bucketname/$TARGET?lang=python#buckets/bucketfsname/bucketname/$TARGET/exaudf/exaudfclient';"
