[tool.poetry]
package-mode = false
name = "exasol-script-languages"
version = "9.2.0"
description = "Script Languages"

license = "MIT"

authors = [
    "Torsten Kilias <torsten.kilias@exasol.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/exasol/script-languages"
homepage = "https://github.com/exasol/script-languages"

keywords = ['exasol', 'udf', 'script-languages']

[tool.poetry.dependencies]
python = ">=3.10,<4"
exasol-script-languages-container-tool = "^2.0.0"
exasol-script-languages-container-ci = "^1.7.0"
exasol-script-languages-container-ci-setup = "^1.7.0"

[tool.poetry.dev-dependencies]
toml = ">=0.10.2"
gitpython = ">=3.1.0"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
