#!/usr/bin/env bash
###

die() { echo "ERROR:" "$@" >&2; exit 1; }

optarr=$(getopt -o 'h' --long 'help,flavor:,test-folder:,generic-test-lang:' -- "$@")

eval set -- "$optarr"

while true; do
    case "$1" in
        --flavor) FLAVOR="$2"; shift 2;;
        --test-folder) test_folder="$2"; shift 2;;
        --generic-test-lang) generic_test_lang="$2"; shift 2;;
        -h|--help) echo "Usage: $0"
		   echo "Options:"
		   echo "  [--flavor]     Choose flavor to test"
		   echo "  [-h|--help]    Print this help."; exit 0;;
        --) shift; break;;
        *) echo "Internal error while parsing arguments. ($1)"; exit 1;;
    esac
done

[ "X$FLAVOR" = "X" ] && die "Missing mandatory argument --flavor"


DB_PORT=$(ls flavors | grep --color=never -n ${FLAVOR} | awk -F ':' '{ print $1+8898 }')
BUCKETFS_PORT=$(ls flavors | grep --color=never -n ${FLAVOR} | awk -F ':' '{ print $1+6593 }')

test_restriction=""

if [ ! -z "${test_folder-}" ]; then
    test_restriction="--test-folder=$test_folder "
fi
if [ ! -z "${generic_test_lang-}" ]; then
    test_restriction+=" --generic-test-lang=$generic_test_lang"
fi



./build --flavor=$FLAVOR && ./export --flavor=$FLAVOR --force && ./clean && ./start_dockerdb --db-port=$DB_PORT --bucketfs-port=$BUCKETFS_PORT && ( cmd="./test --flavor $FLAVOR --use-connection=localhost:$DB_PORT --bucketfs-port=$BUCKETFS_PORT $test_restriction" ; $cmd ) ; ./stop_dockerdb
