load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

skylib_version = "0.8.0"

http_archive(
    name = "bazel_skylib",
    sha256 = "2ef429f5d7ce7111263289644d233707dba35e39696377ebab8b0bc701f7818e",
    type = "tar.gz",
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/{}/bazel-skylib.{}.tar.gz".format(skylib_version, skylib_version),
)

RULES_JVM_EXTERNAL_TAG = "4.2"
RULES_JVM_EXTERNAL_SHA = "cd1a77b7b02e8e008439ca76fd34f5b07aecb8c752961f9640dea15e9e5ba1ca"

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)


load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

load("@rules_jvm_external//:setup.bzl", "rules_jvm_external_setup")

rules_jvm_external_setup()

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.exasol:udf-api-java:1.0.1",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",gi
    ],
)

load("//:python_repository.bzl", "python_local_repository")

python_local_repository(name = "python3")

load("//:python_repository.bzl", "numpy_local_repository")

numpy_local_repository(name = "numpy")

load("//:java_repository.bzl", "java_local_repository")

java_local_repository(name = "java")

load("//:protobuf_repository.bzl", "protobuf_local_repository")

protobuf_local_repository(name = "protobuf")

load("//:zmq_repository.bzl", "zmq_local_repository")
zmq_local_repository(name = "zmq")

new_local_repository(
    name = "ssl",
    build_file_content = """
cc_library(
    name = "ssl",
    srcs = ["usr/lib/x86_64-linux-gnu/libssl.so","usr/lib/x86_64-linux-gnu/libcrypto.so"],
    hdrs = glob(["usr/include/openssl/*.h"]),
    includes = ["usr/include/openssl"],
    visibility = ["//visibility:public"]
)
    """,
    path = "/",
)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "googletest",
    remote = "https://github.com/google/googletest",
    tag = "release-1.11.0",
)
