CREATE SCHEMA TEST;

CREATE TABLE ENGINETABLE (
    INT_INDEX   DECIMAL(18,0),
    DECIMAL1    DECIMAL(8,3),
    DECIMAL2    DECIMAL(8,3),
    SMALLINT1   DECIMAL(9,0),
    SMALLINT2   DECIMAL(9,0),
    INT1        DECIMAL(18,0),
    INT2        DECIMAL(18,0),
    FLOAT1      DOUBLE PRECISION,
    FLOAT2      DOUBLE PRECISION,
    SINGLE_CHAR CHAR(1) UTF8,
    CHAR1       CHAR(30) UTF8,
    CHAR2       CHAR(30) UTF8,
    VARCHAR01   VARCHAR(30) UTF8,
    VARCHAR02   VARCHAR(30) UTF8,
    DATE1       DATE,
    DATE2       DATE
);

CREATE TABLE COMP1 (
    IDX         DECIMAL(18,0),
    CHAR1_1     CHAR(1) UTF8,
    CHAR1_2     CHAR(1) UTF8,
    VARCHAR1_1  VARCHAR(1) UTF8,
    VARCHAR1_2  VARCHAR(1) UTF8,
    CHAR4_1     CHAR(4) UTF8,
    CHAR4_2     CHAR(4) UTF8,
    VARCHAR4_1  VARCHAR(4) UTF8,
    VARCHAR4_2  VARCHAR(4) UTF8,
    CHAR10_1    CHAR(10) UTF8,
    CHAR10_2    CHAR(10) UTF8,
    VARCHAR10_1 VARCHAR(10) UTF8,
    VARCHAR10_2 VARCHAR(10) UTF8
);

CREATE TABLE COMP2 (
    IDX         DECIMAL(18,0),
    CHAR1_1     CHAR(1) UTF8,
    CHAR1_2     CHAR(1) UTF8,
    VARCHAR1_1  VARCHAR(1) UTF8,
    VARCHAR1_2  VARCHAR(1) UTF8,
    CHAR4_1     CHAR(4) UTF8,
    CHAR4_2     CHAR(4) UTF8,
    VARCHAR4_1  VARCHAR(4) UTF8,
    VARCHAR4_2  VARCHAR(4) UTF8,
    CHAR10_1    CHAR(10) UTF8,
    CHAR10_2    CHAR(10) UTF8,
    VARCHAR10_1 VARCHAR(10) UTF8,
    VARCHAR10_2 VARCHAR(10) UTF8
);

CREATE TABLE ENGINETABLETIMESTAMP1 (
    INT_INDEX DECIMAL(18,0),
    TS1       TIMESTAMP
);

CREATE TABLE ENGINETABLETIMESTAMP2 (
    INT_INDEX DECIMAL(18,0),
    TS1       TIMESTAMP
);

CREATE TABLE ENGINETABLEJOIN1 (
    INT_INDEX   DECIMAL(18,0),
    DECIMAL83   DECIMAL(8,3),
    DECIMAL62   DECIMAL(6,2),
    SMALLINT1   DECIMAL(9,0),
    INT1        DECIMAL(18,0),
    FLOAT1      DOUBLE PRECISION,
    SINGLE_CHAR CHAR(1) UTF8,
    CHAR1       CHAR(30) UTF8,
    VARCHAR01   VARCHAR(30) UTF8,
    VARCHAR21   VARCHAR(30) UTF8,
    DATE1       DATE
);

CREATE TABLE ENGINETABLEJOIN2 (
    INT_INDEX   DECIMAL(18,0),
    DECIMAL83   DECIMAL(8,3),
    DECIMAL62   DECIMAL(6,2),
    SMALLINT1   DECIMAL(9,0),
    INT1        DECIMAL(18,0),
    FLOAT1      DOUBLE PRECISION,
    SINGLE_CHAR CHAR(1) UTF8,
    CHAR1       CHAR(30) UTF8,
    VARCHAR01   VARCHAR(30) UTF8,
    VARCHAR21   VARCHAR(30) UTF8,
    DATE1       DATE
);

CREATE TABLE ENGINETABLEJOINSMALL (
    INT_INDEX   DECIMAL(18,0),
    DECIMAL83   DECIMAL(8,3),
    DECIMAL62   DECIMAL(6,2),
    SMALLINT1   DECIMAL(9,0),
    INT1        DECIMAL(18,0),
    FLOAT1      DOUBLE PRECISION,
    SINGLE_CHAR CHAR(1) UTF8,
    CHAR1       CHAR(30) UTF8,
    VARCHAR01   VARCHAR(30) UTF8,
    VARCHAR21   VARCHAR(30) UTF8,
    DATE1       DATE
);

CREATE TABLE JOINTABLE10 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE11 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE12 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE13 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE14 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE15 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE16 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE17 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE18 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE19 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE20 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE21 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0),
    DISTRIBUTE BY COL
);

CREATE TABLE JOINTABLE22 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE JOINTABLE23 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE JOINTABLE24 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE JOINTABLE25 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE JOINTABLE26 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE JOINTABLE27 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE JOINTABLE28 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE JOINTABLE29 (
    INDEX1 DECIMAL(18,0),
    INDEX2 CHAR(3) UTF8,
    COL    DECIMAL(18,0)
);

CREATE TABLE ENGINETABLEJOINOPTCHAR1 (
    INT_INDEX DECIMAL(18,0),
    CHAR1     CHAR(30) UTF8,
    DISTRIBUTE BY CHAR1
);

CREATE TABLE ENGINETABLEJOINOPTCHAR2 (
    INT_INDEX DECIMAL(18,0),
    CHAR1     CHAR(30) UTF8,
    DISTRIBUTE BY CHAR1
);

CREATE TABLE ENGINETABLEJOINOPTVARCHAR1 (
    INT_INDEX DECIMAL(18,0),
    VARCHAR1  VARCHAR(30) UTF8,
    DISTRIBUTE BY VARCHAR1
);

CREATE TABLE ENGINETABLEJOINOPTVARCHAR2 (
    INT_INDEX DECIMAL(18,0),
    VARCHAR1  VARCHAR(30) UTF8,
    DISTRIBUTE BY VARCHAR1
);

CREATE TABLE ENGINETABLEJOINOPTINT1 (
    INT_INDEX DECIMAL(18,0),
    INT1      DECIMAL(18,0),
    DISTRIBUTE BY INT1
);

CREATE TABLE ENGINETABLEJOINOPTINT2 (
    INT_INDEX DECIMAL(18,0),
    INT1      DECIMAL(18,0),
    DISTRIBUTE BY INT1
);

CREATE TABLE ENGINETABLEJOINOPTSMALLINT1 (
    INT_INDEX DECIMAL(18,0),
    SMALLINT1 DECIMAL(9,0),
    DISTRIBUTE BY SMALLINT1
);

CREATE TABLE ENGINETABLEJOINOPTSMALLINT2 (
    INT_INDEX DECIMAL(18,0),
    SMALLINT1 DECIMAL(9,0),
    DISTRIBUTE BY SMALLINT1
);

CREATE TABLE ENGINETABLEJOINOPTFLOAT1 (
    INT_INDEX DECIMAL(18,0),
    FLOAT1    DOUBLE PRECISION,
    DISTRIBUTE BY FLOAT1
);

CREATE TABLE ENGINETABLEJOINOPTFLOAT2 (
    INT_INDEX DECIMAL(18,0),
    FLOAT1    DOUBLE PRECISION,
    DISTRIBUTE BY FLOAT1
);

CREATE TABLE ENGINETABLEJOINOPTDECIMAL1 (
    INT_INDEX DECIMAL(18,0),
    DECIMAL1  DECIMAL(8,3),
    DISTRIBUTE BY DECIMAL1
);

CREATE TABLE ENGINETABLEJOINOPTDECIMAL2 (
    INT_INDEX DECIMAL(18,0),
    DECIMAL1  DECIMAL(8,3),
    DISTRIBUTE BY DECIMAL1
);

CREATE TABLE ENGINETABLEJOINOPTDATE1 (
    INT_INDEX DECIMAL(18,0),
    DATE1     DATE,
    DISTRIBUTE BY DATE1
);

CREATE TABLE ENGINETABLEJOINOPTDATE2 (
    INT_INDEX DECIMAL(18,0),
    DATE1     DATE,
    DISTRIBUTE BY DATE1
);

CREATE TABLE ENGINETABLEJOINOPTTIMESTAMP1 (
    INT_INDEX DECIMAL(18,0),
    TS1       TIMESTAMP,
    DISTRIBUTE BY TS1
);

CREATE TABLE ENGINETABLEJOINOPTTIMESTAMP2 (
    INT_INDEX DECIMAL(18,0),
    TS1       TIMESTAMP,
    DISTRIBUTE BY TS1
);

CREATE TABLE ENGINETABLEBIG1 (
    INT_INDEX DECIMAL(18,0),
    DECIMAL1  DECIMAL(8,3),
    DECIMAL2  DECIMAL(8,3),
    SMALLINT1 DECIMAL(9,0),
    SMALLINT2 DECIMAL(9,0),
    INT1      DECIMAL(18,0),
    INT2      DECIMAL(18,0),
    FLOAT1    DOUBLE PRECISION,
    FLOAT2    DOUBLE PRECISION,
    CHAR1     CHAR(20) UTF8,
    CHAR2     CHAR(20) UTF8,
    VARCHAR01 VARCHAR(20) UTF8,
    VARCHAR02 VARCHAR(20) UTF8,
    DATE1     DATE,
    DATE2     DATE
);

CREATE TABLE ENGINETABLEBIG2 (
    INT_INDEX DECIMAL(18,0),
    DECIMAL1  DECIMAL(8,3),
    SMALLINT1 DECIMAL(9,0),
    INT1      DECIMAL(18,0),
    FLOAT1    DOUBLE PRECISION,
    CHAR1     CHAR(20) UTF8,
    VARCHAR01 VARCHAR(20) UTF8,
    DATE1     DATE
);

CREATE TABLE ENGINETABLEBIGJOINOPTCHAR1 (
    INT_INDEX DECIMAL(18,0),
    CHAR1     CHAR(20) UTF8,
    DISTRIBUTE BY CHAR1
);

CREATE TABLE ENGINETABLEBIGJOINOPTCHAR2 (
    INT_INDEX DECIMAL(18,0),
    CHAR1     CHAR(20) UTF8,
    DISTRIBUTE BY CHAR1
);

CREATE TABLE ENGINETABLEBIGJOINOPTVARCHAR1 (
    INT_INDEX DECIMAL(18,0),
    VARCHAR1  VARCHAR(20) UTF8,
    DISTRIBUTE BY VARCHAR1
);

CREATE TABLE ENGINETABLEBIGJOINOPTVARCHAR2 (
    INT_INDEX DECIMAL(18,0),
    VARCHAR1  VARCHAR(20) UTF8,
    DISTRIBUTE BY VARCHAR1
);

CREATE TABLE ENGINETABLEBIGJOINOPTINT1 (
    INT_INDEX DECIMAL(18,0),
    INT1      DECIMAL(18,0),
    DISTRIBUTE BY INT1
);

CREATE TABLE ENGINETABLEBIGJOINOPTINT2 (
    INT_INDEX DECIMAL(18,0),
    INT1      DECIMAL(18,0),
    DISTRIBUTE BY INT1
);

CREATE TABLE ENGINETABLEBIGJOINOPTSMALLINT1 (
    INT_INDEX DECIMAL(18,0),
    SMALLINT1 DECIMAL(9,0),
    DISTRIBUTE BY SMALLINT1
);

CREATE TABLE ENGINETABLEBIGJOINOPTSMALLINT2 (
    INT_INDEX DECIMAL(18,0),
    SMALLINT1 DECIMAL(9,0),
    DISTRIBUTE BY SMALLINT1
);

CREATE TABLE ENGINETABLEBIGJOINOPTFLOAT1 (
    INT_INDEX DECIMAL(18,0),
    FLOAT1    DOUBLE PRECISION,
    DISTRIBUTE BY FLOAT1
);

CREATE TABLE ENGINETABLEBIGJOINOPTFLOAT2 (
    INT_INDEX DECIMAL(18,0),
    FLOAT1    DOUBLE PRECISION,
    DISTRIBUTE BY FLOAT1
);

CREATE TABLE ENGINETABLEBIGJOINOPTDECIMAL1 (
    INT_INDEX DECIMAL(18,0),
    DECIMAL1  DECIMAL(8,3),
    DISTRIBUTE BY DECIMAL1
);

CREATE TABLE ENGINETABLEBIGJOINOPTDECIMAL2 (
    INT_INDEX DECIMAL(18,0),
    DECIMAL1  DECIMAL(8,3),
    DISTRIBUTE BY DECIMAL1
);

CREATE TABLE ENGINETABLEBIGJOINOPTDATE1 (
    INT_INDEX DECIMAL(18,0),
    DATE1     DATE,
    DISTRIBUTE BY DATE1
);

CREATE TABLE ENGINETABLEBIGJOINOPTDATE2 (
    INT_INDEX DECIMAL(18,0),
    DATE1     DATE,
    DISTRIBUTE BY DATE1
);

CREATE TABLE ENGINETABLEUNICODECHAR (
    C1_INTEGER DECIMAL(18,0),
    C2_CHAR10  CHAR(10) UTF8,
    DISTRIBUTE BY C1_INTEGER,C2_CHAR10
);

CREATE TABLE ENGINETABLEUNICODEVARCHAR (
    C1_INTEGER    DECIMAL(18,0),
    C2_VARCHAR100 VARCHAR(100) UTF8,
    DISTRIBUTE BY C1_INTEGER,C2_VARCHAR100
);

CREATE TABLE ENGINETABLEUNICODE (
    C1_INTEGER    DECIMAL(18,0),
    C2_CHAR10     CHAR(10) UTF8,
    C3_VARCHAR100 VARCHAR(100) UTF8,
    DISTRIBUTE BY C1_INTEGER,C2_CHAR10,C3_VARCHAR100
);

CREATE TABLE ENGINETABLEBIGUNICODECHAR (
    C1_INTEGER DECIMAL(18,0),
    C2_CHAR10  CHAR(10) UTF8,
    DISTRIBUTE BY C1_INTEGER,C2_CHAR10
);

CREATE TABLE ENGINETABLEBIGUNICODEVARCHAR (
    C1_INTEGER    DECIMAL(18,0),
    C2_VARCHAR100 VARCHAR(100) UTF8,
    DISTRIBUTE BY C1_INTEGER,C2_VARCHAR100
);

CREATE TABLE ENGINETABLEBIGUNICODE (
    C1_INTEGER    DECIMAL(18,0),
    C2_CHAR10     CHAR(10) UTF8,
    C3_VARCHAR100 VARCHAR(100) UTF8,
    DISTRIBUTE BY C1_INTEGER,C2_CHAR10,C3_VARCHAR100
);


