#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

REPO_DIR=$(git rev-parse --show-toplevel)
GITHOOKS_PATH="$REPO_DIR/githooks"
pushd "$REPO_DIR"
bash "$GITHOOKS_PATH/prohibit_commit_to_master.sh"
echo "Searching for duplicated error codes in repository (pre-commit hook)"
bash find_duplicate_error_codes.sh
bash "$GITHOOKS_PATH/update_current_submodules_file.sh"
poetry run -- nox -s update-ci-github-workflows
popd
