package(default_visibility = ["//visibility:public"])

cc_library(
    name = "streamingcontainer",
    srcs = ["streamingcontainer.cc","streamingcontainer.h","//exaudflib:header"],
    hdrs = ["streamingcontainer.h"],
    deps = ["//exaudflib:exaudflib-deps"]
)