cc_test(
    name = "script-options-ctpg-parser-test",
    srcs = ["script_option_lines_test.cpp"],
    deps = [
        "//script_options_parser/ctpg:script_option_lines_parser_ctpg",
        "@googletest//:gtest_main",
    ],
)