version: 0.2

env:
  shell: bash
  secrets-manager:
    DOCKER_USER: "Dockerhub:User"
    DOCKER_PASSWORD: "Dockerhub:AccessToken"
phases:

  install:
    runtime-versions:
      python: 3.8
    commands:
      - git submodule update --init --recursive
      - pip3 install --upgrade pip
      - pip3 install "git+https://github.com/exasol/script-languages-container-ci.git@feature/1_add_initial_implementation_of_slc_ci_project"

  pre_build:
      commands:
        - echo CODEBUILD_SOURCE_VERSION is $CODEBUILD_SOURCE_VERSION #supposed to be the SHA
        - echo CODEBUILD_WEBHOOK_HEAD_REF is $CODEBUILD_WEBHOOK_HEAD_REF #supposed to the branch name
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
        - mkdir -p /secrets && echo "$DOCKER_PASSWORD" > "/secrets/DOCKER_PASSWORD"
  #      - bash aws-code-build/scripts/build_or_pull_build_container.sh $_BUILD_DOCKER_REPOSITORY $_DOCKER_USER
  build:
      commands:
        - python3 -m script_languages_container_ci.main run_ci --flavor $FLAVOR --branch-name "$CODEBUILD_WEBHOOK_HEAD_REF" --docker-user "$DOCKER_USER" --docker-build-repository "$BUILD_DOCKER_REPOSITORY" --docker-release-repository "$RELEASE_DOCKER_REPOSITORY" --commit-sha "$CODEBUILD_SOURCE_VERSION"

artifacts:
  files:
      - 'jobs/**/*'
      - 'security_scan/**/*'
  name: build_output_$(date +%Y-%m-%d-%Hh-%Mm-%Ss)
  base-directory: .build_output
  s3-prefix: flavor_$FLAVOR
