version: 0.2

env:
  shell: bash
  variables:
    BUILD_DOCKER_REPOSITORY: "exatk/script-languages-build-cache"
    RELEASE_DOCKER_REPOSITORY: "exasol/script-language-container"
  secrets-manager:
    DOCKER_USER: "Dockerhub:User"
    DOCKER_PASSWORD: "Dockerhub:AccessToken"
phases:

  install:
    runtime-versions:
      python: 3.8
    commands:
      - git submodule update --init --recursive
      - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
      - export PATH=$PATH:$HOME/.poetry/bin
      - poetry env use $(command -v "python3.8")
      - poetry install

  pre_build:
      commands:
        - echo CODEBUILD_SOURCE_VERSION is $CODEBUILD_SOURCE_VERSION #supposed to be the SHA
        - echo CODEBUILD_WEBHOOK_HEAD_REF is $CODEBUILD_WEBHOOK_HEAD_REF #supposed to the branch name
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
  build:
      commands:
        - poetry run python3 -m exasol_script_languages_container_ci.main run-ci --flavor $FLAVOR --branch-name "$CODEBUILD_WEBHOOK_HEAD_REF" --docker-user "$DOCKER_USER" --docker-build-repository "$BUILD_DOCKER_REPOSITORY" --docker-release-repository "$RELEASE_DOCKER_REPOSITORY" --commit-sha "$CODEBUILD_SOURCE_VERSION" --config-file aws-code-build/build_config.json

artifacts:
  files:
      - 'jobs/**/*'
      - 'security_scan/**/*'
  name: build_output_$(date +%Y-%m-%d-%Hh-%Mm-%Ss)
  base-directory: .build_output
  s3-prefix: flavor_$FLAVOR
