version: 0.2

env:
  shell: bash
  variables:
    _BUILD_DOCKER_REPOSITORY: "exatk/script-languages-build-cache"
    _REBUILD: True
  secrets-manager:
    DOCKER_USER: "Dockerhub:User"
    DOCKER_PASSWORD: "Dockerhub:AccessToken"
phases:

  install:
    runtime-versions:
      python: 3.8
    commands:
      - git submodule update --init --recursive
      - mkdir -p secrets
      - echo $DOCKER_PASSWORD > secrets/DOCKER_PASSWORD
      - mkdir -p /workspace
      - pip3 install --upgrade pip
      - pip3 install https://github.com/exasol/script-languages-container-tool/releases/download/0.9.0/exasol_script_languages_container_tool-0.9.0-py3-none-any.whl

pre_build:
    commands:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
  build:
    commands:
      - bash aws-code-build/build/scripts/test.sh $_FLAVOR

artifacts:
  files:
      - 'jobs/**/*'
      - 'security_scan/**/*'
  name: build_output_$(date +%Y-%m-%d-%Hh-%Mm-%Ss)
  base-directory: .build_output
  s3-prefix: flavor_$_FLAVOR

