cc_test(
    name = "exaudflib-test",
    srcs = ["script_data_transfer_objects_test.cpp"],
    deps = [
        "//exaudflib:script_data_transfer_objects",
        "@googletest//:gtest_main",
    ],
)