cc_test(
    name = "exaudflib-test",
    srcs = ["script_data_transfer_objects_test.cpp", "script_option_lines_test.cpp"],
    deps = [
        "//base/exaudflib:script_data_transfer_objects",
        "//base/exaudflib:scriptoptionlines",
        "@googletest//:gtest_main",
    ],
)