FROM {{base_test_build_run}}

RUN mkdir -p /conf /buckets

COPY --from={{flavor_customization}} /usr /usr
RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

COPY --from={{flavor_customization}} /opt /opt
RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

COPY --from={{flavor_customization}} /lib /lib
RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

COPY --from={{flavor_customization}} /bin /bin
RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

COPY --from={{flavor_customization}} /etc /etc
RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

COPY --from={{flavor_customization}} /build_info /build_info
RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965

RUN true # workaround for https://github.com/moby/moby/issues/37965


RUN ldconfig

