package(default_visibility = ["//visibility:public"])
exports_files([
    "exascript_python_preset_core.py",
    "exascript_python_wrap.py",
    "extend_exascript_python_preset_py.sh",
    "python_ext_dataframe.cc",
    "pythoncontainer.cc"
    ])