FROM exaudf/baseimage_standard-exasol-6.0.0

RUN mkdir /exaudf_src /exaudf_src/build /exaudf

COPY src/ /exaudf_src/

RUN /exaudf_src/build_client.sh \
    --src-dir=/exaudf_src \
    --build-dir=/exaudf_src/build \
    --output-dir=/exaudf \
    --enable-python \
    --enable-r \
    --enable-java \
    --release-sources \
    --java-flags="-L/usr/lib/jvm/java-9-openjdk-amd64/jre/lib/amd64 -L/usr/lib/jvm/java-9-openjdk-amd64/jre/lib/amd64/server -Wl,-rpath,/usr/lib/jvm/java-9-openjdk-amd64/lib/amd64 -Wl,-rpath,/usr/lib/jvm/java-9-openjdk-amd64/jre/lib/amd64/server -I/usr/lib/jvm/java-9-openjdk-amd64/include -I/usr/lib/jvm/java-9-openjdk-amd64/include/linux"
