package(default_visibility = ["//visibility:public"])

cc_library(
    name = "script_option_lines_parser",
    hdrs = ["script_option_lines.h"],
    srcs = ["script_option_lines.cc","script_option_lines.h"],
    copts= ["-fno-lto"],
)
