package(default_visibility = ["//visibility:public"])

cc_library(
    name = "scriptoptionlinesparser",
    hdrs = ["scriptoptionlines.h"],
    srcs = ["scriptoptionlines.cc","scriptoptionlines.h"],
    copts= ["-fno-lto"],
)
