#!/bin/sh

import sys, os


sys.path.insert(0,os.path.realpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')))

import container as top_container


if __name__ == "__main__":
    top_container.run_container(sys.argv)
