#!/usr/bin/env bash
set -ue


## CMD Functions: Help
_cmd_help()
{
  cat <<EOF
Usage:

    c4 make [CMD]

Defined build and install interface of C4 for generic integration of the nvidia driver libraries into c4.

Commands:

    c4 make                  # build and install of nvidia driver user libraries
    c4 make build            # build of nvidia driver user libraries
    c4 make install          # install of nvidia driver user libraries
    c4 make clean            # remove all artifacts

    c4 make test             # Run tests - CURRENTLY UNUSED

EOF
}

FLAVOR=standard-EXASOL-7.0.0
EXASUITE=EXASuite-7
EXARUNTIME=@EXARuntime-7.0.dev1
EXARUNTIME_PATH=EXARuntime-7.0.dev1
EXASLCT_TMP="$HOME/exaslct-tmp"
export PATH=/usr/opt/${EXASUITE}/${EXARUNTIME_PATH}/bin:$PATH
INSTALL_PATH="$BUILDSYSTEM_LINKDIR/install"
EXPORT_PATH="$BUILDSYSTEM_LINKDIR"

get_image_hash()
{
  cat "$BUILDSYSTEM_LINKDIR/install/build_info/image_info/$FLAVOR-release" \
  | jq -r .hash | cut -c 1-8
}

## CMD Functions: General C4 Query Commands - Not explicitly used by the user 
_cmd_prefix() {
    HASH=$(get_image_hash)
    HASH=${HASH:-NOHASH}

    PREFIX=/usr/opt/${EXASUITE}/ScriptLanguages-${FLAVOR}-${HASH}
    echo "$PREFIX"
    exit "$?"
}

_cmd_provides() {
  echo script-language-${FLAVOR}
}

_cmd_requires() {
  echo
}

_cmd_build() {
  mkdir -p "$EXASLCT_TMP"
  "$CCC_CCC" extract -m ${EXARUNTIME}

  mkdir -p "$BUILDSYSTEM_LINKDIR"
  PIP_INSTALL=YES ./exaslct export --flavor-path="flavors/${FLAVOR}" --export-path "$EXPORT_PATH" --temporary-base-directory "$EXASLCT_TMP" \
  && mkdir "$INSTALL_PATH" \
  && for f in "$EXPORT_PATH/"*.gz; do tar xfC "$f" "$INSTALL_PATH"; done
}

_cmd_clean() {
  ./exaslct clean-flavor-images --flavor-path "flavors/${FLAVOR}"
  rm -rf "$EXASLCT_TMP"
  rm -rf "$INSTALL_PATH"
  rm -rf "$EXPORT_PATH/"*.gz
}

_cmd_test() {
  ./exaslct run-db-test --flavor-path "flavors/${FLAVOR}"
}

## Command Switch
if [ "$1" = prefix ]; then
  _cmd_prefix
elif [ "$1" = make ]; then
  _cmd_build
elif [ "$1" = clean ]; then
  _cmd_clean
elif [ "$1" = provides ]; then
  _cmd_provides
elif [ "$1" = requires ]; then
  _cmd_requires
elif [ "$1" = test ]; then
  shift
  _cmd_test "$@"
elif [ "$1" = help-more ]; then # help is already in use by main c4 path
  _cmd_help
else
  _cmd_help
fi
