#!/bin/bash

make_container()
{
  mkdir -p $HOME/exaslct-tmp


  "$CCC_CCC" extract -m @EXARuntime-7.0.dev1
  sed -i 's/python_version = "3.6"/python_version = "3.7"/g' Pipfile
  export PATH=/usr/opt/EXASuite-7/EXARuntime-7.0.dev1/bin:$PATH

  mkdir -p "$BUILDSYSTEM_LINKDIR"
  PIP_INSTALL=YES ./exaslct export --flavor-path=flavors/standard-EXASOL-6.1.0 --export-path "$BUILDSYSTEM_LINKDIR" --temporary-base-directory $HOME/exaslct-tmp
}

test_container()
{
  export PATH=/usr/opt/EXASuite-7/EXARuntime-7.0.dev1/bin:$PATH
  ./exaslct run-db-test --flavor-path flavors/standard-EXASOL-6.1.0
}

case "$1" in
  make)
    make_container
    exit "$?"
  ;;
  test)
    test_container
    exit "$?"
  ;;
#  install)
#    export BUILDSYSTEM_PKGDIR=/x/pkg
#    export SRC_DIR=${PWD}
#    mkdir -p .build/
#    cd .build || exit 1
#    bash "${BUILDER}" install
#    exit "$?"
#  ;;
#  package)
#    export BUILDSYSTEM_PKGDIR=/x/pkg
#    export SRC_DIR=${PWD}
#    mkdir -p .build/
#    cd .build || exit 1
#    bash "${BUILDER}" package
#    exit "$?"
#  ;;
#  clean)
#    rm -rf .build/
#    exit "$?"
#  ;;
  help)
    show_usage
    exit 0
  ;;
esac
