/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exasol_udf_java_test_JNITest */

#ifndef _Included_com_exasol_udf_java_test_JNITest
#define _Included_com_exasol_udf_java_test_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exasol_udf_java_test_JNITest
 * Method:    runTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_exasol_udf_java_test_JNITest_runTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
