cc_test(
    name = "exaudflib-test",
    srcs = ["script_data_transfer_objects_test.cpp", "script_option_lines_test.cpp"],
    deps = [
        "//exaudf/exaudflib:script_data_transfer_objects",
        "//exaudf/exaudflib:scriptoptionlines",
        "@googletest//:gtest_main",
    ],
)