FROM exaudf/baseimage_python3-ds-exasol-6.0.0

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y curl openjdk-8-jdk && \
	echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
	curl https://bazel.build/bazel-release.pub.gpg | apt-key add - && \
	apt-get update && apt-get install -y bazel

RUN mkdir /exaudf_src /exaudf
COPY src/ /exaudf_src/

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk-amd64
ENV PYTHON3_PREFIX /usr
ENV PYTHON3_VERSION python3.6
ENV CUSTOM_PROTOBUF_BIN /usr/local/bin/protoc
ENV CUSTOM_PROTOBUF_PREFIX /usr/local/lib
#ENV VERBOSE_BUILD "--subcommands --verbose_failures"

RUN cd /exaudf_src/ && \
	bash build.sh --define python=true //:exaudfclient_py3 && \
	cp -r -L bazel-bin/* /exaudf
