#!/usr/bin/env bash

# AUTOGENERATED FILE.
# Do not modify the installed version. Check source:
# https://github.com/exasol/script-languages-container-tool/blob/main/exasol_script_languages_container_tool/starter_scripts/construct_docker_runner_image_name.sh

set -euo pipefail

if [ -z "${1-}" ]; then
  VERSION="$(git rev-parse HEAD 2>/dev/null || echo latest)"
else
  VERSION="$1"
fi

echo "exasol/script-language-container:container-tool-runner-$VERSION"
