FROM exaudf/baseimage_python3_16

RUN mkdir /exaudf_src /exaudf_src/build /exaudf

COPY src/ /exaudf_src/

RUN /exaudf_src/build_client.sh --src-dir=/exaudf_src --build-dir=/exaudf_src/build --output-dir=/exaudf --enable-python3 --custom-protobuf-prefix=/usr/local
