FROM exaudf/release_tensorflow

RUN mkdir /exasol_emulator

COPY emulator/ /exasol_emulator
COPY src/exaudflib/zmqcontainer.proto /exasol_emulator

#RUN pip install protobuf==3.5.1
RUN     apt-get -y install python-zmq

RUN cd /exasol_emulator && protoc zmqcontainer.proto --python_out=.
RUN ls /exasol_emulator
