
#load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")


git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.2"
)

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

new_local_repository(
    name = "python_2_7_linux",
    path = "/usr",
    build_file_content = """
cc_library(
    name = "python27-lib",
    srcs = ["lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so"],
    hdrs = glob(["include/python2.7/*.h"]),
    includes = ["include/python2.7"],
    visibility = ["//visibility:public"]
)
    """
)

new_local_repository(
    name = "R_linux",
    path = "/usr",
    build_file_content = """
cc_library(
    name = "r-lib",
    srcs = glob(["share/R/include/*/*.h","share/R/include/*.h"]),
    hdrs = glob(["share/R/include/*/*.h","share/R/include/*.h"]),
    includes = ["share/R/include"],
    visibility = ["//visibility:public"]
)
    """
)

