package(default_visibility = ["//visibility:public"])
exports_files([
    "exascript_python_preset_core.py",
    "exascript_python_wrap.py",
    "extend_exascript_python_preset_py.sh",
    "pythoncontainer.cc"
    ])

cc_library(
    name = "pythoncontainer_header",
    hdrs = ["pythoncontainer.h"]
)