package(default_visibility = ["//visibility:public"])

cc_library(
    name = "script_option_lines_parser_legacy",
    hdrs = ["script_option_lines.h"],
    srcs = ["script_option_lines.cc"],
    deps = ["//script_options_parser:exception"],
    copts= ["-fno-lto"],
)
