name: Build SLC

on:
  workflow_call:
    inputs:
      flavor:
          description: 'A flavor'
          required: true
          type: string
jobs:

  detect-runner:
    runs-on: ubuntu-22.04
    steps:
     - uses: actions/checkout@v4
     - name: Setup Python & Poetry Environment
       uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
       with:
         python-version: '3.10'
         poetry-version: '2.1.2'
     - name: Detect runner
       id: detect-runner
       run: |
         RUNNER=$(poetry run nox -s "get-build-runner-for-flavor(flavor='${{ inputs.flavor }}')")
         echo "runner=$RUNNER" >> "$GITHUB_OUTPUT"
    outputs:
     runner: ${{ steps.detect-runner.outputs.runner }}
  build:
    needs: detect-runner
    runs-on:
      labels: ${{needs.detect-runner.outputs.runner}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          python-version: '3.10'
          poetry-version: '2.1.2'
      - name: Check space on disk
        run: df
      - name: Build SLC ${{ inputs.flavor }}
        run: |
          mkdir slc
          poetry run exaslct export --flavor-path "flavors/${{inputs.flavor}}" --export-path ./slc
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: slc_${{inputs.flavor}}
          path: ./slc/*.tar.gz
          compression-level: 0