name: Check Markdown links

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/markdown_check_config.json'
