name: Check starter scripts

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Init submodules
      run: git submodule update --init --recursive

    - uses: ./.github/actions/prepare_poetry_env

    - name: Setup Python & Poetry Environment
      uses: exasol/python-toolbox/.github/actions/python-environment@0.12.0
      with:
        python-version: "3.10"
        poetry-version: '1.8.2'

    - name: Run githooks/update_exaslct_starter_scripts.sh
      run: bash githooks/update_exaslct_starter_scripts.sh

    - name: Check git status
      run: bash scripts/check_git_status.sh
