name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  get-flavors:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.20.0
        with:
          python-version: '${{ matrix.python_version }}'
          poetry-version: '2.1.2'
      - id: set-matrix
        run: |
          FLAVORS=$(poetry run nox -s get-flavors)
          echo "matrix=$FLAVORS" >> "$GITHUB_OUTPUT"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  ci:
    needs: get-flavors
    strategy:
      fail-fast: true
      matrix:
        flavor: ${{fromJson(needs.get-flavors.outputs.matrix)}}
    uses: ./.github/workflows/ci_flavor.yaml
    with:
      flavor: ${{ matrix.flavor }}

