name: CI

on:
  workflow_call:
    inputs:
      flavor:
          description: 'A flavor'
          required: true
          type: string
    outputs:
      continue:
        description: "Indicates if need to build and test SLC"
        value: ${{ jobs.check_for_build.outputs.continue }}

jobs:
  check_for_build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@1.0.1
        with:
          python-version: "3.10"
          poetry-version: "2.1.2"
      - name: Run check
        id: run-check
        run: |
          branch_name="${{github.head_ref || github.ref_name}}"
          result=$(poetry run -- nox -s  ci:check-if-build-need -- --flavor ${{ inputs.flavor }} --branch-name "$branch_name")
          echo "continue=$result" >> $GITHUB_OUTPUT

    outputs:
      continue: ${{ steps.run-check.outputs.continue }}
