name: CI

on:
  workflow_call:
    inputs:
      flavor:
          description: 'A flavor'
          required: true
          type: string

jobs:

  build:
    uses: ./.github/workflows/build_slc.yaml
    with:
      flavor: ${{ inputs.flavor }}
  test:
    needs: [build]
    uses: ./.github/workflows/test_slc.yaml
    with:
      flavor: ${{ inputs.flavor }}