name: OFT Report

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run HTML Report
        run: |
          bash .github/workflows/scripts/run_oft.sh ./exaudfclient base -o html -f ./oft_report.html -t V2,_ || echo failed
      - name: Run Plaintext Report
        run: |
          bash .github/workflows/scripts/run_oft.sh ./exaudfclient base -t V2,_
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "oft_report.html"
          path: oft_report.html
