FROM exaudf/release_python3-ds-exasol-6.0.0

RUN apt-get -y install python-protobuf python-zmq gdb protobuf-compiler

RUN mkdir /exasol_emulator
COPY emulator/ /exasol_emulator
COPY src/exaudflib/zmqcontainer.proto /exasol_emulator

RUN cd /exasol_emulator && /usr/bin/protoc zmqcontainer.proto --python_out=.
RUN ls /exasol_emulator